### ISSUE TITLE
Add Notebook 1 : Python Basics

### ISSUE THREAD

**Issue by MYCIN-AI-Club** [MYCIN-AI-Club/ML-Guide#1]
Follow the readme for procedure

**Comment by Garvit414** [comment]
I would like to contribute to this issue.
Please assign it to me @MYCIN-AI-Club.

**Comment by ayu3011** [comment]
I started my journey in python and ML recently. So i would request @MYCIN-AI-Club to please assign this issue to me as it will help me learn more.

**Comment by MYCIN-AI-Club** [comment]
@Garvit414 Do you have issue assigned to you?

**Comment by Garvit414** [comment]
> @Garvit414 Do you have issue assigned to you?

No

**Comment by MYCIN-AI-Club** [comment]
you have been assigned the issue @Garvit414 . Submit the files in Jupyter Notebook format only!

**Comment by Garvit414** [comment]
> you have been assigned the issue @Garvit414 . Submit the files in Jupyter Notebook format only!

Okk
