### ISSUE TITLE
Add Notebook 2 : Python Functions

### ISSUE THREAD

**Issue by MYCIN-AI-Club** [MYCIN-AI-Club/ML-Guide#2]
Follow the readme for rules.

**Comment by vansri24** [comment]
I find myself skilled enough to solve the issues please assign me the same.

**Comment by MYCIN-AI-Club** [comment]
Great @vansri24 ! Your initiative is appreciated. Please prepare the Notebook using Google Colab, with proper headings and code snippets. Have a great coding time!!

**Comment by cyborg-joshi** [comment]
i find myself capable to do this task. may I @MYCIN-AI-Club ? IF ITS NOT YET DONE
